# Generated by Django 6.0.5 on 2026-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=150, verbose_name='Место проведения')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время')),
                ('max_guests', models.IntegerField(verbose_name='Макс. гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['event_date'],
            },
        ),
    ]
